### ISSUE TITLE
when trying to `uploadDirectory`, I get unexpected `Error: Agent has no proofs for did:key:`

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3up#1153]
# questions

* [x] why am I seeing the error below `Error: Agent has no proofs for did:key:z6MkmhSfj45TA7FbfybdciiS8zPAwmSSmAMdjco7GgH1Zizt.`
  * It's because I was assume `client.createSpace` and created the space->clientAgent authorization and added it there, but I guess it hadn't.

# how I reproduce the bug

`ex3.mjs`:
```javascript
import * as Client from '@web3-storage/w3up-client'
import { filesFromPaths } from 'files-from-path'

const client = await Client.create()
console.log('client', client.did())

// get an email to use for the w3up account that will control the space
const inputEmail = process.env.W3UP_EMAIL

// account associated with input email
let myAccount
if (inputEmail) {
  console.warn(`about to w3up client.login with email ${inputEmail}`)
  myAccount = await client.login(inputEmail)
}

const sharkDaoSpace = await client.createSpace('sharkDAO.xyz')

if (myAccount) {
  console.warn(`account ${myAccount.did()} is adding a provider to space ${sharkDaoSpace.did()}`)
  await myAccount.provision(sharkDaoSpace.did())
}

// this is what was missing but I didn't know it at the time
// await client.addSpace(await sharkDaoSpace.createAuthorization(client))
await client.setCurrentSpace(sharkDaoSpace.did())
const sharkPics = await client.uploadDirectory(await filesFromPaths(['./sharkdao788.jpg']))

await sharkDaoSpace.save()
console.log(sharkPics.toString())
```

```
bengo@bengo ~/learnyouw3up-1700160524 ⚡  W3UP_EMAIL='bengo@dag.house' node ex3.mjs
client did:key:z6MksBKapybzpXbFAmt2QVNcNGVQo2mtZHHvUe24GUQsXtsT
couponRedemption GrantedAccess {
  model: {
    agent: Agent { url: [URL], connection: [Connection] },
    proofs: [ [Delegation] ]
  }
}
about to w3up client.login with email bengo@dag.house
provisioning sharkDaoSpace using account did:mailto:dag.house:bengo
file:///Users/bengo/node_modules/@web3-storage/access/dist/src/agent.js:327
            throw new Error(`Agent has no proofs for ${space}.`);
                  ^

Error: Agent has no proofs for did:key:z6MkmhSfj45TA7FbfybdciiS8zPAwmSSmAMdjco7GgH1Zizt.
    at Agent.setCurrentSpace (file:///Users/bengo/node_modules/@web3-storage/access/dist/src/agent.js:327:19)
    at Client.setCurrentSpace (file:///Users/bengo/node_modules/@web3-storage/w3up-client/src/client.js:200:23)
    at file:///Users/bengo/learnyouw3up-1700160524/ex3.mjs:41:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.2
```

**Comment by gobengo** [comment]
ugh I was missing this
```
await client.addSpace(await sharkDaoSpace.createAuthorization(client))
```

**Comment by gobengo** [comment]
i'm gonna sleep on it but rn I'm thinking that `W3upClient#createSpace` should have gone ahead and done the `createAuthorization(client)` earlier when I did `client.createSpace()`.

fyi there is no mention of `createAuthorization()` in learnyouw3up. I found it by reading some tests/srccode

**Comment by gobengo** [comment]
(yes, I was doing more than the 'solution' for ex3 by making my own space and stuff. But idk that's what felt right, and seems reasonable in a workshop like learnyou)

**Comment by gobengo** [comment]
@Gozala is it as designed that I'm required to pass that above? `await client.addSpace(await sharkDaoSpace.createAuthorization(client))`

If so, we should maybe have it in a learnyou module. But I also kinda think it feels like I shouldn't have to. (and in slack you posted expected usage that did not show `client.addSpace`)

**Comment by gobengo** [comment]
I noticed that @orpheuslummis also filed https://github.com/web3-storage/w3up/issues/1212 (linking)

**Comment by gobengo** [comment]
I confirmed with @Gozala that the API is working as intended. 

In my snippet above, I need to uncomment
```
// await client.addSpace(await sharkDaoSpace.createAuthorization(client))
```

or, alterantively, I learned that this should also work `await sharkDaoSpace.save()`

**Comment by rubycop** [comment]
same issue. very poor doc!
```
const client = await create();
await client.setCurrentSpace(
  process.env.REACT_APP_WEB3_STORAGE as `did:${string}:${string}`
);
```
