### ISSUE TITLE
Logging-in from a new machine or after a reinstalling breaks both the CLI and the Client, if there were old delegations 

### ISSUE THREAD

**Issue by chrlyz** [web3-storage/w3up#1235]
After reinstalling the CLI and Client I started getting those errors when trying to log-in or set a space (the same happened when I tried to log-in from another machine with a fresh Ubuntu 22.04.3 installation):

`CLI`
```console
ParseError: Can't parse UCAN: : Expected JWT format: 3 dot-separated base64url-encoded values.
    at ParseError.throw (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:325:11)
    at Module.fail (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:332:47)
    at parse (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/parser.js:19:21)
    at Module.decode (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/codec/jwt.js:36:27)
    at Module.decode (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/lib.js:52:16)
    at decode (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:437:23)
    at get data [as data] (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:230:18)
    at get attachedLinks [as attachedLinks] (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:181:27)
    at Delegation.export (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:249:51)
    at AgentData.export (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/access/dist/src/agent-data.js:87:56)

Node.js v18.17.1
```

`Client`
```console
ParseError: Can't parse UCAN: : Expected JWT format: 3 dot-separated base64url-encoded values.
    at ParseError.throw (file:///home/chrlyz/wrdhom_server/node_modules/@ipld/dag-ucan/src/schema.js:325:11)
    at Module.fail (file:///home/chrlyz/wrdhom_server/node_modules/@ipld/dag-ucan/src/schema.js:332:47)
    at parse (file:///home/chrlyz/wrdhom_server/node_modules/@ipld/dag-ucan/src/parser.js:19:21)
    at Module.decode (file:///home/chrlyz/wrdhom_server/node_modules/@ipld/dag-ucan/src/codec/jwt.js:36:27)
    at Module.decode (file:///home/chrlyz/wrdhom_server/node_modules/@ipld/dag-ucan/src/lib.js:52:16)
    at decode (file:///home/chrlyz/wrdhom_server/node_modules/@ucanto/core/src/delegation.js:437:23)
    at get data [as data] (file:///home/chrlyz/wrdhom_server/node_modules/@ucanto/core/src/delegation.js:230:18)
    at get expiration [as expiration] (file:///home/chrlyz/wrdhom_server/node_modules/@ucanto/core/src/delegation.js:295:17)
    at isExpired (file:///home/chrlyz/wrdhom_server/node_modules/@web3-storage/access/dist/src/delegations.js:9:20)
    at #delegations (file:///home/chrlyz/wrdhom_server/node_modules/@web3-storage/access/dist/src/agent.js:159:18)
    at Agent.proofs (file:///home/chrlyz/wrdhom_server/node_modules/@web3-storage/access/dist/src/agent.js:234:55)
    at list (file:///home/chrlyz/wrdhom_server/node_modules/@web3-storage/w3up-client/src/account.js:29:24)
    at Module.login (file:///home/chrlyz/wrdhom_server/node_modules/@web3-storage/w3up-client/src/account.js:97:19)
    at Client.login (file:///home/chrlyz/wrdhom_server/node_modules/@web3-storage/w3up-client/src/client.js:83:49)
    at file:///home/chrlyz/wrdhom_server/build/service.js:14:19

Node.js v18.17.1
```
The issue seems to be that when I log-in and generate my new `~/.config/w3access` JSON files, the `bytes` properties are empty (i.e. `"bytes": {}`) for `delegations`, so when those files get parsed, the null values cause the error. If I manually remove the delegations from my `~/.config/w3access` JSON files, I'm able to log-in and set spaces, but then when I try to do something like `w3 ls` with the CLI, I get this error (similar for `w3 up`):

```console
file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/dist/src/upload.js:139
        throw new Error(`failed ${UploadCapabilities.list.can} invocation`, {
              ^

Error: failed upload/list invocation
    at Module.list (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/dist/src/upload.js:139:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async list (file:///usr/local/lib/node_modules/@web3-storage/w3cli/index.js:171:11) {
  [cause]: {
    name: 'Unauthorized',
    stack: 'Unauthorized: Claim {"can":"upload/list"} is not authorized\n' +
      '  - Capability {"can":"upload/list","with":"did:key:z6Mkj6kybvJKUYQNCGvg7vKPayZdn272rPLsVQzF8oDAV8B7"} is not authorized because:\n' +
      "    - Capability can not be (self) issued by 'did:key:z6MkuZVeT8cQU6XiY1PGvSzM69KtX45MKHxFdYBo5EyHeRzz'\n" +
      '    - Delegated capability not found\n' +
      '    at claim (/node_modules/@ucanto/validator/src/lib.js:308:12)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at Object.list (/node_modules/@ucanto/server/src/handler.js:61:27)\n' +
      '    at invoke2 (/node_modules/@ucanto/server/src/server.js:145:23)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at execute (/node_modules/@ucanto/server/src/server.js:104:5)\n' +
      '    at ucanInvocationRouter (/upload-api/functions/ucan-invocation-router.js:260:20)\n' +
      '    at Runtime.handler (/node_modules/src/awslambda.ts:332:1)',
    message: 'Claim {"can":"upload/list"} is not authorized\n' +
      '  - Capability {"can":"upload/list","with":"did:key:z6Mkj6kybvJKUYQNCGvg7vKPayZdn272rPLsVQzF8oDAV8B7"} is not authorized because:\n' +
      "    - Capability can not be (self) issued by 'did:key:z6MkuZVeT8cQU6XiY1PGvSzM69KtX45MKHxFdYBo5EyHeRzz'\n" +
      '    - Delegated capability not found'
  }
}

Node.js v18.17.1
```

Interestingly, if I delete my `w3up-client.json` file or the last delegations, I'm able to log-in, set the space, and even upload as many files as long as I don't kill the node process from where I'm doing this (after killing the process, I get the `ParseError: Can't parse UCAN: : Expected JWT format: 3 dot-separated base64url-encoded values.` error again when trying to log-in or set the space), so I guess that the issue is related to how the data for the delegations is loaded?

**Comment by travis** [comment]
Thanks for the bug report @chrlyz! Could you provide more detailed reproduction instructions for this bug? I'm not sure how to get my environment into the same state yours is in. Thank you!

**Comment by chrlyz** [comment]
If you delete your `~/.config/w3access` directory, and then log-in again, everything keeps working, @travis?

**Comment by travis** [comment]
That directory doesn't exist on my machine.

**Comment by chrlyz** [comment]
I see, but I guess there should be somewhere on every machine where the `w3cli.json` and `w3up-client.json` files are stored, to store the principal agent DID, keys, spaces, and delegations, right?

I also suspect that I may be having this particular issue from the time I was trying [this](https://web3.storage/docs/how-to/upload/#bring-your-own-agent) example, and was getting the `Error: missing capabilities for delegation` error that got fixed in `@web3-storage/w3cli@5.1.0` after I reported it.

I'm just speculating, but could it be that when I tried creating those delegations, those got created for my account, the keys for those agents were stored on my `w3cli.json` / `w3up-client.json` files, but then when those got rewritten/erased I lost the keys, and when I log-in, my regenerated files for my account include those old delegations but with empty keys (since those just were available on my machine). Or those delegations got created on a corrupted way for my account or something like that.

**Comment by alanshaw** [comment]
@travis 😟 my guess is that [conf](https://www.npmjs.com/package/conf) is not playing with `ArrayBuffer` nicely.

**Comment by travis** [comment]
that's it! I've released a new version of w3cli to fix this by rolling back the access-client dependency and am working on a proper bugfix similar to the hack in https://github.com/web3-storage/w3cli/issues/143

**Comment by chrlyz** [comment]
Cool, it looks like this fixed it for `@web3-storage/w3cli`, although I'm still seeing the same issue for `@web3-storage/w3up-client`. Also, I'm curious.To what exactly each `cid` in the `delegations` property points to, and what data `bytes` contains?

**Comment by travis** [comment]
great - I've just released a new version of w3up-client that should fix this for you. you may need to initialize a new store - the existing store likely has some delegations that have been incorrectly set to `{}` 

the `delegations` property contains a list of IPLD blocks that represent a `Delegation` created here: https://github.com/web3-storage/ucanto/blob/main/packages/core/src/delegation.js#L500

the bytes are the bytes of the block and the CID is the CID of those bytes

**Comment by chrlyz** [comment]
Now it's working, thanks! 🙌
