### ISSUE TITLE
upload-client incompatible with Vercel (automatic headers can't be set because some object is not extensible)

### ISSUE THREAD

**Issue by npfoss** [web3-storage/w3up#1254]
here's the raw error from the Vercel console, for code which works locally but fails when deployed:
```txt
TypeError: Cannot add property x-vercel-id, object is not extensible
    at X (/var/task/___vc/__launcher/bridge-server-72TT5FOD.js:1:6045)
    at Object.mutateHeaders (/var/task/___vc/__launcher/bridge-server-72TT5FOD.js:2:1032)
    at /var/task/___vc/__launcher/bridge-server-72TT5FOD.js:1:887
    at /var/task/___vc/__launcher/bridge-server-72TT5FOD.js:1:4769
    at _optionalChain (/var/task/___vc/__launcher/bridge-server-72TT5FOD.js:1:865)
    at d (/var/task/___vc/__launcher/bridge-server-72TT5FOD.js:1:4691)
    at Channel.request (file:///var/task/node_modules/@ucanto/transport/src/http.js:60:33)
    at execute (file:///var/task/node_modules/@ucanto/client/src/connection.js:50:45)
    at async IssuedInvocation.execute (file:///var/task/node_modules/@ucanto/core/src/invocation.js:115:22)
    at async retry.onFailedAttempt (file:///var/task/node_modules/@web3-storage/upload-client/dist/src/store.js:52:16)
```

My guess is Vercel is automatically adding headers on all outgoing requests, but internally the ucanto lib is doing something "extra safe" and making the request an un-extensible object before Vercel then tries to edit it

**Comment by alanshaw** [comment]
Yes https://github.com/web3-storage/ucanto/blob/2200d43595b85a5e7b60c234987ff3ce91404401/packages/transport/src/car/response.js#L7-L9

**Comment by npfoss** [comment]
Thanks for jumping on this so quickly!

Do you have any workaround ideas in the meantime (easier than forking the package myself)? A naive `Object.preventExtensions = () => {}` didn't fix it :P

**Comment by alanshaw** [comment]
@npfoss should be ok now if you ensure `@ucanto/transport@9.0.1` is in your dependency tree.

**Comment by npfoss** [comment]
ah fantastic, thank you!!

**Comment by npfoss** [comment]
this didn't fix it @alanshaw -- I think maybe we need to tweak request.js, not response.js? I interpreted this error as Vercel trying to add an id to outgoing requests, plus the API call doesn't show an effect (in the storage console) so I think it's failing on the way out, not the way back

sorry the devloop on this is so slow -- if this doesn't work I can try forking and modifying stuff until it works? Unless you have ideas for how to repro it locally (I'm just not sure how to modify the reqs at the level Vercel is -- I'm sure there's a way)

**Comment by alanshaw** [comment]
Urgh, ok try again with `9.0.2`
