### ISSUE TITLE
`uploadCar` fails to upload .car file but `uploadfile` works

### ISSUE THREAD

**Issue by aarontravass** [web3-storage/w3up#872]
For the w3up-client, when I try to upload a car file using the `uploadCar` function, it fails and gives these errors.

```log
Error: CBOR decode error: simple values are not supported
    at file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/jump.js:20:11
    at Tokeniser.next (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:31:15)
    at tokensToObject (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:95:27)
    at tokenToArray (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:42:19)
    at tokensToObject (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:103:12)
    at Module.decode (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:123:19)
    at decode (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+dag-cbor@9.0.4/node_modules/@ipld/dag-cbor/src/index.js:117:39)
    at readHeader (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+car@5.2.0/node_modules/@ipld/car/src/decoder.js:33:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+car@5.2.0/node_modules/@ipld/car/src/decoder.js:147:20
```

```log
Error: CBOR decode error: not enough data for type
    at assertEnoughData (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/common.js:11:11)
    at Module.readUint64 (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/0uint.js:41:3)
    at decodeTag64 (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/6tag.js:19:35)
    at Tokeniser.next (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:31:15)
    at tokensToObject (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:95:27)
    at Module.decode (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:123:19)
    at decode (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+dag-cbor@9.0.4/node_modules/@ipld/dag-cbor/src/index.js:117:39)
    at readHeader (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+car@5.2.0/node_modules/@ipld/car/src/decoder.js:33:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+car@5.2.0/node_modules/@ipld/car/src/decoder.js:147:20
```

```log
Error: CBOR decode error: too many terminals, data makes no sense
    at Module.decode (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/cborg@2.0.5/node_modules/cborg/esm/lib/decode.js:131:11)
    at decode (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+dag-cbor@9.0.4/node_modules/@ipld/dag-cbor/src/index.js:117:39)
    at readHeader (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+car@5.2.0/node_modules/@ipld/car/src/decoder.js:33:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+car@5.2.0/node_modules/@ipld/car/src/decoder.js:147:20
    at async decodeIterator (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+car@5.2.0/node_modules/@ipld/car/src/iterator.js:281:30)
    at async CarBlockIterator.fromIterable (file:///C:/Users/aaron/Documents/projects/flash/api/node_modules/.pnpm/@ipld+car@5.2.0/node_modules/@ipld/car/src/iterator.js:134:42)
```

Moreover, these errors happen in particular order. Although `uploadFile` works but I am not sure why `uploadCar` doesn't. Any idea what is happening?

**Comment by dchoi27** [comment]
i also get an error, but using w3cli `w3 up -c`

```
1 file (0.3KB)
⠋ Storingfile:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/src/car.js:50
          const bytes = await car.arrayBuffer()
                                  ^

TypeError: car.arrayBuffer is not a function
    at file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/src/car.js:50:35
    at getBlocksIterable (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/src/car.js:52:11)
    at Object.start (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/src/car.js:63:30)
    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2385:23)
    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2418:3)
    at new ReadableStream (node:internal/webstreams/readablestream:289:7)
    at new BlockStream (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/src/car.js:61:5)
    at uploadCAR (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/src/index.js:99:18)
    at Client.uploadCAR (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/w3up-client/src/client.js:100:12)
    at async upload (file:///usr/local/lib/node_modules/@web3-storage/w3cli/index.js:71:16)
```

**Comment by alanshaw** [comment]
@dchoi27 you need to use node.js 18 for the time being.

@aarontravass can you provide the CAR file you're trying to upload and the code that you're using to call the function? It looks like it is having trouble reading the CAR file.

**Comment by aarontravass** [comment]
Here is the code
```ts
  return (await w3sUpClient.uploadCAR(carFile))
    .then((cid: any) => cid.toString())
    .catch((error: any) => {
      throw new W3StorageSpaceError('FILE_UPLOAD', (error as Error).message, error)
    })
}
```
carFile is of type File

and this is the car file I'm trying to upload 
https://drive.google.com/file/d/1VaMr_bF7dlap6JC-hAwLfUNL7LJyFjEd/view?usp=sharing

**Comment by alanshaw** [comment]
How are you obtaining the file?

**Comment by dchoi27** [comment]
I think he's asking how the CAR file was generated!

**Comment by alanshaw** [comment]
No I mean how are you reading it into your program? Where does the variable `carFile` come from?

**Comment by aarontravass** [comment]
Here's the code

```ts
builder.mutationField('uploadCar', (t) =>
  t.field({
    args: {
      storageProviderId: t.arg.id(),
      carFile: t.arg({
        type: 'File',
        required: true
      })
    },
   
    resolve: async (query, { storageProviderId, carFile }, ctx) => {
     
```

type `File` comes from
```ts
builder.scalarType('File', {
  serialize: () => {
    throw new Error('File Uploads can only be used as input types')
  }
})
```

I'm using pothos for building the schema

**Comment by aarontravass** [comment]
The upload was based on 

https://github.com/dotansimha/graphql-yoga/blob/75ee8523b5507ab44947abfd6e8fe612baee1ada/examples/file-upload-nextjs-pothos/schema.ts#L7-L35

**Comment by aarontravass** [comment]
@alanshaw any updates on the solution?

**Comment by kprigel** [comment]
The documentation appears to be incorrect.  I dug into the CLI implementation, and this is the code that I found works to upload a CAR file:

const uploadCarToWeb3 = async (file) => {
  const inStream = readFileSync(file);
  const blob = new Blob([inStream]);
  const web3Client = await web3NewClient();
  const cid = await web3Client.uploadCAR(blob);
  return cid;
};

**Comment by gobengo** [comment]
@aarontravass I tried to reproduce the above, but was unable to. Here is a little script where I tried to reproduce the bug, but failed. It shows how upload a car file using `uploadCAR`. https://github.com/gobengo/w3up-issue-872/blob/main/upload-car.js

> The upload was based on
> 
> https://github.com/dotansimha/graphql-yoga/blob/75ee8523b5507ab44947abfd6e8fe612baee1ada/examples/file-upload-nextjs-pothos/schema.ts#L7-L35

I looked at this too. I haven't used pothos before, but I think the issue may be here. Are you sure that pothos is giving you [this kind of `File`]()?

> carFile is of type File

Can you do `console.log(carFile)` and share what it says?

Can you also share the base64-encoded file contents? (the file you linked to above is not accessible to me)
```js
console.warn('base64(car)', await base64File(file))

/**
 * @param {File} file 
 */
async function base64File(file) {
  const bytes = new Uint8Array(await file.arrayBuffer())
  const text = [...bytes].map(b => String.fromCharCode(b)).join('')
  const b64 = btoa(text)
  return b64
}
```

**Comment by aarontravass** [comment]
Hey @gobengo, apologies for the late response! Looks like the new version may have fixed this bug. I'm going to upgrade and have a look.

**Comment by gobengo** [comment]
@aarontravass How did it go? 🤞

**Comment by aarontravass** [comment]
@gobengo Current plans are to rethink authentication. Nevertheless, I ended up creating an example repository to test upload https://github.com/aarontravass/pothos-w3up

Could be useful to someone I guess.

**Comment by gobengo** [comment]
@aarontravass Thanks! If I'm understanding right, it looks like now you're using `uploadCar` and it's working ok? I hope so!
https://github.com/aarontravass/pothos-w3up/blob/main/src/mutations.ts#L48

Reopen this if it gives you any errors and I'll look into it
