### ISSUE TITLE
ability to setup delegations on space creation

### ISSUE THREAD

**Issue by jchris** [web3-storage/w3up#876]
Maybe passing a function in, or some delegations. Some way to add additional capabilities.

I get why the key is thrown away. It would be cool if there was a way to delegate eg `clock/*` from the space to the agent or account owner or whoever gets the other delegations here:

https://github.com/web3-storage/w3up/blob/77e4d7de219b8d07ffc29a53836573dba6be0897/packages/access-client/src/agent.js#L275

Currently I'm trying to delegate `clock/*` like this:

```js
   const delegated = await clock.delegate({
        issuer: ag.issuer,
        audience: DID.parse('did:web:clock.web3.storage'),
        with: space.did(),
        proofs: claims
      })
```

And get this error (makes sense because the issuer should be the space not the agent):

```
{
    "name": "Unauthorized",
    "stack": "Unauthorized: Claim {\"can\":\"clock/advance\"} is not authorized\n  - Capability {\"can\":\"clock/advance\",\"with\":\"did:key:z6MkoiijC3VwkDCZvyQrXp5EaLMRb5Rjg2TwoNBKXxbmfspx\",\"nb\":{\"event\":{\"/\":\"bafyreidpyh3fwvwp3c25f5wysxb6gteeu2qmetjttlp6225nsnzujdmj7q\"}}} is not authorized because:\n    - Capability can not be (self) issued by 'did:key:z4MXj1wBzi9jUstyQJMGNPnZcpp8XKET4MzgA4vxuA9Na5uytdwjw2QgWWskFhRdmw3rXo3ZMsob46f9WCvsps1pkJ3hencAaVeHFW3XcGWsZnXAjEigoCpLAj5f2cxR7Rf53xPoPjymCWAW5yL6v18zmRT1EucamQeCz5ShnQT3FjZFMJy12X9ynkkkneNjffa2z87i8v247M6hfLYGRGYpaDMKE9T5WzxCiEYGdRGaESdhXu4eoqoR8pmNfEFt3F3ytqDLkKbZJg9uyGReBpxKQrCucf6iCDdRDrq4fYK7AujeJr8A8U7N3hPoCabJpqkyB7FgJcKvA1gsiCBQsiSakHfH6DkNgM3TGrg1rUsTtzQsjuJQg'\n    - Capability can not be derived from prf:bafyreigrhy5q355kfalox6qn5cslfdzuk7r3pxhps7ixxk6unl74lstooa because:\n      - Delegation audience is 'did:web:clock.web3.storage' instead of 'did:key:z4MXj1wBzi9jUstyQJMGNPnZcpp8XKET4MzgA4vxuA9Na5uytdwjw2QgWWskFhRdmw3rXo3ZMsob46f9WCvsps1pkJ3hencAaVeHFW3XcGWsZnXAjEigoCpLAj5f2cxR7Rf53xPoPjymCWAW5yL6v18zmRT1EucamQeCz5ShnQT3FjZFMJy12X9ynkkkneNjffa2z87i8v247M6hfLYGRGYpaDMKE9T5WzxCiEYGdRGaESdhXu4eoqoR8pmNfEFt3F3ytqDLkKbZJg9uyGReBpxKQrCucf6iCDdRDrq4fYK7AujeJr8A8U7N3hPoCabJpqkyB7FgJcKvA1gsiCBQsiSakHfH6DkNgM3TGrg1rUsTtzQsjuJQg'\n    at Li (worker.js:5120:19)\n    at async Object.advance (worker.js:5980:11)\n    at async gf (worker.js:5828:13)\n    at async Promise.all (index 0)\n    at async Sg (worker.js:5818:51)\n    at async bg (worker.js:5813:71)\n    at async Ng (worker.js:6029:84)\n    at async worker.js:4551:14\n    at async worker.js:4544:13",
    "message": "Claim {\"can\":\"clock/advance\"} is not authorized\n  - Capability {\"can\":\"clock/advance\",\"with\":\"did:key:z6MkoiijC3VwkDCZvyQrXp5EaLMRb5Rjg2TwoNBKXxbmfspx\",\"nb\":{\"event\":{\"/\":\"bafyreidpyh3fwvwp3c25f5wysxb6gteeu2qmetjttlp6225nsnzujdmj7q\"}}} is not authorized because:\n    - Capability can not be (self) issued by 'did:key:z4MXj1wBzi9jUstyQJMGNPnZcpp8XKET4MzgA4vxuA9Na5uytdwjw2QgWWskFhRdmw3rXo3ZMsob46f9WCvsps1pkJ3hencAaVeHFW3XcGWsZnXAjEigoCpLAj5f2cxR7Rf53xPoPjymCWAW5yL6v18zmRT1EucamQeCz5ShnQT3FjZFMJy12X9ynkkkneNjffa2z87i8v247M6hfLYGRGYpaDMKE9T5WzxCiEYGdRGaESdhXu4eoqoR8pmNfEFt3F3ytqDLkKbZJg9uyGReBpxKQrCucf6iCDdRDrq4fYK7AujeJr8A8U7N3hPoCabJpqkyB7FgJcKvA1gsiCBQsiSakHfH6DkNgM3TGrg1rUsTtzQsjuJQg'\n    - Capability can not be derived from prf:bafyreigrhy5q355kfalox6qn5cslfdzuk7r3pxhps7ixxk6unl74lstooa because:\n      - Delegation audience is 'did:web:clock.web3.storage' instead of 'did:key:z4MXj1wBzi9jUstyQJMGNPnZcpp8XKET4MzgA4vxuA9Na5uytdwjw2QgWWskFhRdmw3rXo3ZMsob46f9WCvsps1pkJ3hencAaVeHFW3XcGWsZnXAjEigoCpLAj5f2cxR7Rf53xPoPjymCWAW5yL6v18zmRT1EucamQeCz5ShnQT3FjZFMJy12X9ynkkkneNjffa2z87i8v247M6hfLYGRGYpaDMKE9T5WzxCiEYGdRGaESdhXu4eoqoR8pmNfEFt3F3ytqDLkKbZJg9uyGReBpxKQrCucf6iCDdRDrq4fYK7AujeJr8A8U7N3hPoCabJpqkyB7FgJcKvA1gsiCBQsiSakHfH6DkNgM3TGrg1rUsTtzQsjuJQg'"
}
```

**Comment by jchris** [comment]
one reason I might be diagnosing the issue wrong is that `top` should give my agent the ability to delegate `clock/*`

https://github.com/web3-storage/w3up/blob/main/packages/capabilities/src/top.js

**Comment by jchris** [comment]
happy to screen share my debugger environment if that will help

**Comment by Gozala** [comment]
I see that error says following

```
Capability can not be derived from prf:bafyreigrhy5q355kfalox6qn5cslfdzuk7r3pxhps7ixxk6unl74lstooa because:
     - Delegation audience is 'did:web:clock.web3.storage' instead of 'did:key:z4MXj1wBzi9jUstyQJMGNPnZcpp8XKET4MzgA4vxuA9Na5uytdwjw2QgWWskFhRdmw3rXo3ZMsob46f9WCvsps1pkJ3hencAaVeHFW3XcGWsZnXAjEigoCpLAj5f2cxR7Rf53xPoPjymCWAW5yL6v18zmRT1EucamQeCz5ShnQT3FjZFMJy12X9ynkkkneNjffa2z87i8v247M6hfLYGRGYpaDMKE9T5WzxCiEYGdRGaESdhXu4eoqoR8pmNfEFt3F3ytqDLkKbZJg9uyGReBpxKQrCucf6iCDdRDrq4fYK7AujeJr8A8U7N3hPoCabJpqkyB7FgJcKvA1gsiCBQsiSakHfH6DkNgM3TGrg1rUsTtzQsjuJQg
```

Where `prf:bafyreigrhy5q355kfalox6qn5cslfdzuk7r3pxhps7ixxk6unl74lstooa` refers to the proof inside the `claims` you pass.

In other words I think proof in claims has `did:web:clock.web3.storage` in the audience field as opposed to `ag.issuer` which performs the redelegation. Since `ag.issuer` has not been delegated capability it can not re-delegate it.

More simply you always need to align proof audience with delegation issuer.

**Comment by jchris** [comment]
I think I don't have access to delegate like I need to, which is why it doesn't work. I'm trying to patch `createSpace` to accept a set of additional delegatoins but I don't think I understand enough of the story.

**Comment by jchris** [comment]
this seems to have been based on state from one of my legacy accounts. will reopen if I get stuck in the same place again on a fresh account

**Comment by jchris** [comment]
It works on the client that created the space, but not on other clients that get access to it via email.

Here is the client setup code: https://github.com/fireproof-storage/fireproof/blob/daf5981ab04f8bdc15c59c1417b827b7d158f27a/packages/fireproof/src/connect-web3.ts#L134

Here is a screenshot. The browser on the left is the one that originated the space. The one on the right is the one that logged in:
<img width="2056" alt="Screen Shot 2023-09-06 at 1 52 14 PM" src="https://github.com/web3-storage/w3up/assets/253/a566509c-7031-48ac-a503-a53bbabbe602">
